import Head from 'next/head'
import { ReactNode } from 'react'
import { TextareaContainer } from '@/container/text-area-container'
import HeaderContainer from '@/container/header-container'

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="mx-auto flex justify-center items-center">
      <Head>
        <title>Sharelink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="height-100vh w-[480px] flex flex-col">
        <div className="sticky top-0">
          <HeaderContainer />
          <TextareaContainer></TextareaContainer>
        </div>

        <main className="container mx-auto p-4">{children}</main>
      </div>
    </div>
  )
}
